### PR TITLE
Update Alpine to 3.9, Ubuntu to 18.04.

### PR DESCRIPTION
**Pull request by dinogun**

### CODE REVIEW

**Comment by dinogun** [comment]
@arthurdm Updating both the Base OS (Alpine and Ubuntu) and glibc for Alpine. Appreciate if you can test the update to make sure nothing breaks for your apps. Thanks !
The test images are at [here](https://hub.docker.com/r/dinogun/j9/tags).
@dnwe Would be great if you can do a quick test as well, Thanks !

**Comment by dinogun** [comment]
Waiting on a pending legal approval before I can merge this, is taking much longer than I thought. Current ETA is 01-Apr.

**Comment by dinogun** [comment]
Since the legal approval is taking a lot longer than anticipated, merged the glibc 2.20-r0 changes in a separate PR (#61). This PR is now only to upgrade Alpine 3.9 and Ubuntu 18.04

**Comment by arthurdm** [comment]
Any updates on this one?   We are fixing Liberty's support config page to include Ubuntu 18.04

**Comment by strouja** [comment]
Legal stuff drives me nuts as it takes months to do things that should take 15 minutes.  Anyway if it helps we've been running the latest IBM JREs on Ubuntu 18.04.2 and they work fine
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
```
I did notice that our OS is running an older version of glibc
```
wlpadmin@fci-case-manager-fci-solution-667bd6f579-79mrj:/$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27

```

Also Alpine 3.10.0 is out and we should use that instead of 3.9.x.

**Comment by davidkarlsen** [comment]
IBM in a nutshell.

**Comment by cblomart** [comment]
Saw the pull request too late... we would like to upgrade alpine to 3.10 to avoid CVEs in 3.7

**Comment by arthurdm** [comment]
any updates on this one @dinogun?

**Comment by dinogun** [comment]
Closing this in favour of #78.

**Pull request closed without merging**
