### PR TITLE
fix: minor tidyup of JAVA_URL sed expr

### PR DESCRIPTION
**Pull request by dnwe**

### CODE REVIEW

**Comment by dnwe** [comment]
I'm not sure why travis is failing as I can build all the images manually and `make test` passes fine for me locally.

**Comment by dinogun** [comment]
It works for me locally too, can you try JAVA_VERSION in braces ?

**Comment by dnwe** [comment]
@dinogun so it turns out the Travis failure is unrelated to my commit and sees to be a change in the upstream base alpine image and/or with public.dhe.ibm.com such that TLS handshaking done by busybox wget is no longer working. From the latest build logs:
```
 + wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta//sfj/linux/x86_64/index.yml
 ssl_client: public.dhe.ibm.com: TLS connect failed
 wget: error getting response: Connection reset by peer
```

This is reproducible in a plain alpine:3.6 image:
```
~ docker pull alpine:3.6 ; docker run --rm alpine:3.6 wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta//sfj/linux/x86_64/index.yml
3.6: Pulling from library/alpine
Digest: sha256:de5701d6a3a36dc6a5db260d21be0422fd30dd2d158c1e048b34263e73205cb6
Status: Image is up to date for alpine:3.6
ssl_client: public.dhe.ibm.com: TLS connect failed
wget: error getting response: Connection reset by peer
```

**Comment by dnwe** [comment]
I've pushed a commit to just install and use full wget on alpine for the fetching (removing it within the same layer). Hopefully that fixes this issue.

**Comment by dinogun** [comment]
Thanks @dnwe for debugging this issue as well as all the cleanups. LGTM ! Will bump up alpine to 3.7 in a short bit also.

**Pull request merged**
