### PR TITLE
Adding RHEL Dockerfile

### PR DESCRIPTION
**Pull request by arthurdm**
This PR updates the `update.sh` script to generate a RHEL Dockerfile.  

Fixes issue #34

### CODE REVIEW

**Comment by arthurdm** [comment]
@dinogun - here's the update we discussed in #34         

Let me know if I can help clarify any part of it.

**Comment by dinogun** [comment]
LGTM. Do you want to generate the Dockerfiles in a subsequent PR ?

**Comment by arthurdm** [comment]
thx @dinogun - added the generated files.

**Comment by dinogun** [comment]
Couple of more questions, sorry.
1. I assume you only want the jre dockerfile to be generated and not sdk and sfj ? (Which is fine)
2. It would be good to state in the README.md that these files are for ease of use and no corresponding docker images would be present.

**Comment by arthurdm** [comment]
Hey @dinogun - good question.  I think definitely not the SDK, but I am now wondering if we should use the sfj for lower footprint.   What's the main difference between the two?  

I will update the README.md.

**Comment by dinogun** [comment]
More information on the SFJ can be found [here](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.80.doc/user/small_jre.html).

**Comment by arthurdm** [comment]
Thanks @dinogun - at this time we'll just expose the JRE RHEL Dockerfile.

**Comment by dinogun** [comment]
LGTM

**Pull request merged**
